services:
  db:
    image: postgres
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports: 
      - 5432:5432

volumes:
  dbdata:
