export default [
	{
		name: 'Addi Spimel',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 6,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Aglai Soul P',
		slotName: 'Soul',
		bp: 11,
		hp: 0,
		pp: 5,
		melPot: 2.5,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ael Note D',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Stamel',
		slotName: 'Addi',
		bp: 10,
		hp: 20,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Deftmel',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2.5,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Guamel',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Secreta I',
		slotName: 'Secreta',
		bp: 3,
		hp: -10,
		pp: 0,
		melPot: 1,
		rngPot: 1,
		tecPot: 1,
		potFloor: 1,
		dmgResist: -1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Guara',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Guatech',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Defttech',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 2.5,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Spitech',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 6,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Deftra',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 2.5,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Staspitech',
		slotName: 'Addi',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ael Domina',
		slotName: 'Domina',
		bp: 8,
		hp: 5,
		pp: 3,
		melPot: 1.5,
		rngPot: 1.5,
		tecPot: 1.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Stara',
		slotName: 'Addi',
		bp: 10,
		hp: 20,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deft Technique',
		slotName: 'Technique',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ams Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Lostral Note',
		slotName: 'Note',
		bp: 5,
		hp: 10,
		pp: 0,
		melPot: 1.25,
		rngPot: 1.25,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Might I',
		slotName: 'Might',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 1,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Esperio II',
		slotName: 'EXP',
		bp: 0,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 450
	},
	{
		name: 'Dust Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Thali Soul H',
		slotName: 'Soul',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ragras Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Technique III',
		slotName: 'Gigas',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Guard II',
		slotName: 'Guard',
		bp: 3,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 1.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Spiromel',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: -3,
		melPot: 2.25,
		rngPot: 0,
		tecPot: null,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pain Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 30,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pettas Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ret Note A',
		slotName: 'Note',
		bp: 5,
		hp: 10,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spi Technique',
		slotName: 'Technique',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Shock Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 25,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Wind Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 2.5,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Wardmel',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 20,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Wardra',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 20,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Statech',
		slotName: 'Addi',
		bp: 10,
		hp: 20,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Crocys Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dolz Soul I',
		slotName: 'Soul',
		bp: 5,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 1,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ams Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Soul III',
		slotName: 'Soul',
		bp: 9,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Daityl Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 0,
		pp: 5,
		melPot: 1,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Hi Perio',
		slotName: 'EXP',
		bp: 0,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 5000
	},
	{
		name: 'Maqea Note',
		slotName: 'Note',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 1.25,
		rngPot: 1.25,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Resola Note',
		slotName: 'Note',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 1.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Machini Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Sand Soul III',
		slotName: 'Soul',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Technique I',
		slotName: 'Gigas',
		bp: 6,
		hp: 5,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 1.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pettas Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Precision III',
		slotName: 'Precision',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ratech Dualble III',
		slotName: 'Ble',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1.75,
		tecPot: 1.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Stamina I',
		slotName: 'Stamina',
		bp: 3,
		hp: 5,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Thali Soul P',
		slotName: 'Soul',
		bp: 11,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Staromel',
		slotName: 'Tria',
		bp: 6,
		hp: -5,
		pp: 0,
		melPot: 2.25,
		rngPot: 0,
		tecPot: null,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Staspira',
		slotName: 'Addi',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gua Technique',
		slotName: 'Technique',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Blind Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 20,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Soul II',
		slotName: 'Soul',
		bp: 7,
		hp: 10,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Crocys Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 1,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deftness I',
		slotName: 'Deftness',
		bp: 3,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 1,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Megas Fusia',
		slotName: 'Fusia',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 1,
		rngPot: 1,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Fire Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 2.5,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Eradi Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 10,
		pp: 4,
		melPot: 2.25,
		rngPot: 2.25,
		tecPot: 2.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Freeze Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 25,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Nex Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Technique II',
		slotName: 'Technique',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 1.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Poison Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 30,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ragras Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Guarora',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.25,
		tecPot: null,
		potFloor: 0,
		dmgResist: -1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Renus Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ret Note D',
		slotName: 'Note',
		bp: 4,
		hp: 5,
		pp: 0,
		melPot: 0,
		rngPot: 0.75,
		tecPot: 0.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Wardtech',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 20,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Soul I',
		slotName: 'Soul',
		bp: 5,
		hp: 5,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Staspimel',
		slotName: 'Addi',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Euphroy Soul P',
		slotName: 'Soul',
		bp: 11,
		hp: 0,
		pp: 5,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Burn Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 30,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sta Precision',
		slotName: 'Precision',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deft Precision',
		slotName: 'Precision',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dolz Soul II',
		slotName: 'Soul',
		bp: 6,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gua Might',
		slotName: 'Might',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dust Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Precision III',
		slotName: 'Gigas',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Freeze Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 30,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Soul III',
		slotName: 'Soul',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Mastery I',
		slotName: 'Mastery',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0.5,
		rngPot: 0.5,
		tecPot: 0.5,
		potFloor: 0.5,
		dmgResist: 0.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Kvar Note A',
		slotName: 'Note',
		bp: 5,
		hp: 10,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Kvar Note B',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: -2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Panic Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 25,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Nex Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ratech Dualble II',
		slotName: 'Ble',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1.25,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Shock Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 20,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Renus Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spi Might',
		slotName: 'Might',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Starotech',
		slotName: 'Tria',
		bp: 6,
		hp: -5,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Spirotech',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: -3,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Addi Spira',
		slotName: 'Addi',
		bp: 10,
		hp: 0,
		pp: 6,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Daityl Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 0,
		pp: 5,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Might III',
		slotName: 'Might',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Technique',
		slotName: 'Decold',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 25,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Precision I',
		slotName: 'Precision',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Eradi Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 10,
		pp: 4,
		melPot: 1.75,
		rngPot: 1.75,
		tecPot: 1.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Euphroy Soul X',
		slotName: 'Soul',
		bp: 11,
		hp: 10,
		pp: 3,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Freeze Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 20,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Frostyl Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 10,
		pp: 3,
		melPot: 1,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dark Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 2.5,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ice Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 2.5,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Lightning Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 2.5,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ragras Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 1,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sta Might',
		slotName: 'Might',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Starora',
		slotName: 'Tria',
		bp: 6,
		hp: -5,
		pp: 0,
		melPot: 0,
		rngPot: 2.25,
		tecPot: null,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Spirora',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: -3,
		melPot: 0,
		rngPot: 2.25,
		tecPot: null,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Might II',
		slotName: 'Might',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 1.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Blind Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 30,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pettas Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 1,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deft Might',
		slotName: 'Might',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dread Keeper III',
		slotName: 'Keeper',
		bp: 10,
		hp: 30,
		pp: 7,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Euphroy Soul H',
		slotName: 'Soul',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Machini Soul III',
		slotName: 'Soul',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Precision II',
		slotName: 'Precision',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Frostyl Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Guard I',
		slotName: 'Guard',
		bp: 2,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Lab Note',
		slotName: 'Note',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 1.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Renus Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sovereign Ward II',
		slotName: 'Ward',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 25,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Technique I',
		slotName: 'Technique',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Thali Soul X',
		slotName: 'Soul',
		bp: 11,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gua Precision',
		slotName: 'Precision',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ratech Dualble I',
		slotName: 'Ble',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0.75,
		tecPot: 0.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Daityl Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Might',
		slotName: 'Decold',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 25,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Precision II',
		slotName: 'Gigas',
		bp: 8,
		hp: 10,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dolz Soul III',
		slotName: 'Soul',
		bp: 7,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2.5,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Kvar Note C',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: -2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Sand Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Frostyl Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 10,
		pp: 3,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ret Note B',
		slotName: 'Note',
		bp: 4,
		hp: 5,
		pp: 0,
		melPot: 0.75,
		rngPot: 0.75,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Light Exploit I',
		slotName: 'Exploit',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 2.5,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Shock Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 30,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Meltech Dualble III',
		slotName: 'Ble',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 1.75,
		rngPot: 0,
		tecPot: 1.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Panic Ward III',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 30,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spi Precision',
		slotName: 'Precision',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sta Technique',
		slotName: 'Technique',
		bp: 8,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Deftromel',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 2.25,
		rngPot: 0,
		tecPot: null,
		potFloor: -1,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Belgan Note',
		slotName: 'Note',
		bp: 5,
		hp: 0,
		pp: 3,
		melPot: 1.25,
		rngPot: 1.25,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Kvar Note D',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 2,
		potFloor: 0,
		dmgResist: -2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Crocys Soul III',
		slotName: 'Soul',
		bp: 10,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Eradi Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 10,
		pp: 4,
		melPot: 1.25,
		rngPot: 1.25,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dust Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 15,
		pp: 0,
		melPot: 1,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Sand Soul I',
		slotName: 'Soul',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Machini Soul I',
		slotName: 'Soul',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ret Note C',
		slotName: 'Note',
		bp: 4,
		hp: 5,
		pp: 0,
		melPot: 0.75,
		rngPot: 0,
		tecPot: 0.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Thali',
		slotName: 'Gigas',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Technique II',
		slotName: 'Gigas',
		bp: 8,
		hp: 10,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Magnus Note',
		slotName: 'Note',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 1.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spirit I',
		slotName: 'Spirit',
		bp: 2,
		hp: 0,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Meltech Dualble II',
		slotName: 'Ble',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 1.25,
		rngPot: 0,
		tecPot: 1.25,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Poison Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 20,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Panic Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 20,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ret Domina',
		slotName: 'Domina',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 1.5,
		rngPot: 1.5,
		tecPot: 1.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Triplble',
		slotName: 'Ble',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 2,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Guarotech',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.25,
		potFloor: 0,
		dmgResist: -1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ael Note C',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 1,
		rngPot: 0,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Secreta II',
		slotName: 'Secreta',
		bp: 4,
		hp: -10,
		pp: 0,
		melPot: 1.5,
		rngPot: 1.5,
		tecPot: 1.5,
		potFloor: 1.5,
		dmgResist: -1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Blind Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 25,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dread Keeper I',
		slotName: 'Keeper',
		bp: 7,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 1,
		dmgResist: 1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Standard I',
		slotName: 'Decold',
		bp: 1,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 5,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Might I',
		slotName: 'Gigas',
		bp: 6,
		hp: 5,
		pp: 0,
		melPot: 1.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spirit III',
		slotName: 'Spirit',
		bp: 4,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ael Note B',
		slotName: 'Note',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 1,
		rngPot: 1,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Stamina III',
		slotName: 'Stamina',
		bp: 5,
		hp: 15,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Deftrora',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.25,
		tecPot: null,
		potFloor: -1,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Aglai Soul X',
		slotName: 'Soul',
		bp: 11,
		hp: 10,
		pp: 3,
		melPot: 2.5,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deftness III',
		slotName: 'Deftness',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Melra Dualble I',
		slotName: 'Ble',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0.75,
		rngPot: 0.75,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Aglai Soul H',
		slotName: 'Soul',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Precision I',
		slotName: 'Gigas',
		bp: 6,
		hp: 5,
		pp: 0,
		melPot: 0,
		rngPot: 1.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Guard III',
		slotName: 'Guard',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Melra Dualble III',
		slotName: 'Ble',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 1.75,
		rngPot: 1.75,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Stamina II',
		slotName: 'Stamina',
		bp: 4,
		hp: 10,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Guaromel',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 2.25,
		rngPot: 0,
		tecPot: null,
		potFloor: 0,
		dmgResist: -1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ael Note A',
		slotName: 'Note',
		bp: 5,
		hp: 5,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Might III',
		slotName: 'Gigas',
		bp: 10,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Mastery II',
		slotName: 'Mastery',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 1,
		rngPot: 1,
		tecPot: 1,
		potFloor: 1,
		dmgResist: 1,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alno Note',
		slotName: 'Note',
		bp: 5,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 2,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Burn Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 20,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Standard III',
		slotName: 'Decold',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 25,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Esperio I',
		slotName: 'EXP',
		bp: 0,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 400
	},
	{
		name: 'Gigas Aglai',
		slotName: 'Gigas',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Mastery III',
		slotName: 'Mastery',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 1.5,
		rngPot: 1.5,
		tecPot: 1.5,
		potFloor: 1.5,
		dmgResist: 1.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Spirit II',
		slotName: 'Spirit',
		bp: 3,
		hp: 0,
		pp: 4,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Alts Secreta III',
		slotName: 'Secreta',
		bp: 5,
		hp: -10,
		pp: 0,
		melPot: 2,
		rngPot: 2,
		tecPot: 2,
		potFloor: 2,
		dmgResist: -1.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Dread Keeper II',
		slotName: 'Keeper',
		bp: 7.5,
		hp: 15,
		pp: 4,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 1.5,
		dmgResist: 1.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Euphroy',
		slotName: 'Gigas',
		bp: 11,
		hp: 15,
		pp: 0,
		melPot: 2.5,
		rngPot: 0,
		tecPot: 2.5,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Mastery IV',
		slotName: 'Mastery',
		bp: 12,
		hp: 0,
		pp: 0,
		melPot: 2.5,
		rngPot: 2.5,
		tecPot: 2.5,
		potFloor: 2.5,
		dmgResist: 2.5,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Meltech Dualble I',
		slotName: 'Ble',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0.75,
		rngPot: 0,
		tecPot: 0.75,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Burn Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 25,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Standard II',
		slotName: 'Decold',
		bp: 3,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 15,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Ams Soul I',
		slotName: 'Soul',
		bp: 7,
		hp: 10,
		pp: 3,
		melPot: 0,
		rngPot: 0,
		tecPot: 1,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Decold Precision',
		slotName: 'Decold',
		bp: 9,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 2.5,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 25,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Melra Dualble II',
		slotName: 'Ble',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 1.25,
		rngPot: 1.25,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Technique III',
		slotName: 'Technique',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Deftness II',
		slotName: 'Deftness',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 1.5,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Soul I',
		slotName: 'Soul',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pain Ward I',
		slotName: 'Ward',
		bp: 4,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 20,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Forms Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Tria Deftrotech',
		slotName: 'Tria',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 2.25,
		potFloor: -1,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Gigas Might II',
		slotName: 'Gigas',
		bp: 8,
		hp: 10,
		pp: 0,
		melPot: 2,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Kvar Domina',
		slotName: 'Domina',
		bp: 10,
		hp: 0,
		pp: 5,
		melPot: 2,
		rngPot: 2,
		tecPot: 2,
		potFloor: 0,
		dmgResist: -2,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Pain Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 25,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Nex Soul II',
		slotName: 'Soul',
		bp: 8,
		hp: 0,
		pp: 5,
		melPot: 0,
		rngPot: 0,
		tecPot: 2,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Poison Ward II',
		slotName: 'Ward',
		bp: 5,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 25,
		painResist: 0,
		allResist: 0,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sovereign Ward III',
		slotName: 'Ward',
		bp: 10,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 30,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	},
	{
		name: 'Sovereign Ward I',
		slotName: 'Ward',
		bp: 6,
		hp: 0,
		pp: 0,
		melPot: 0,
		rngPot: 0,
		tecPot: 0,
		potFloor: 0,
		dmgResist: 0,
		burnResist: 0,
		freezeResist: 0,
		shockResist: 0,
		blindResist: 0,
		panicResist: 0,
		poisonResist: 0,
		painResist: 0,
		allResist: 20,
		firePot: 0,
		icePot: 0,
		lightningPot: 0,
		windPot: 0,
		lightPot: 0,
		darkPot: 0,
		lowTempResist: 0,
		daytimePot: 0,
		nighttimePot: 0,
		expGrind: 0
	}
];
